# Generated by Django 3.2.8 on 2021-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="Hi, I'm using DayPlanner to discover my city!"),
        ),
    ]
