# Generated by Django 3.2.8 on 2021-11-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="daycategory",
            constraint=models.UniqueConstraint(
                fields=("day", "cat"), name="unique_daycat"
            ),
        ),
    ]
