from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Day(models.Model):
    # primary key is auto generated by django
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tmp = models.TextField(default="Some String")
    # creator = user.primary_key
    # daydetails = models.ForeignKey(DayVenues) --> does not exist yet.
    # DayVenues should at least have:
    #   1. all yelp business id
    #   2. order of yelp business id.
    #   3. created date.
