# Generated by Django 3.2.7 on 2021-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='tmp',
            field=models.TextField(default='Some String'),
        ),
    ]
