# Generated by Django 3.2.7 on 2021-10-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0002_dayvenue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayvenue",
            options={"ordering": ["pos"]},
        ),
    ]
