# Generated by Django 3.2.7 on 2021-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_days_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
