# Generated by Django 3.2.8 on 2021-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0005_day_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
