# Generated by Django 3.2.7 on 2021-11-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('days', '0006_alter_day_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Created at')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoriteday',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='favoriteday_unique_user_day'),
        ),
    ]
